### ISSUE TITLE
Develop help tooltip component

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#101]
There should be a component for help text.
I want to add help texts to various elements and need a ( i ) element that displays the text on click/hover.
Would be great if the text was also available on the page bottom (to find it without knowing the element)

**Comment by matthias-luger** [comment]
in the tooltip-component branch i implemented a versatile and easy to use tooltip component. It can be used to show text by hovering over a element or it can open a dialog by clicking on it.

- Are there any further requirement?
- Where should the component be used?
- What do you mean by "Would be great if the text was also available on the page bottom"

**Comment by Ekwav** [comment]
* There are currently no further requirements
* On every filter to explain what it filters for
* To allow google to index the text it could be displayed at the bottom of the page.
