### ISSUE TITLE
Create Group Cards 

### ISSUE THREAD

**Issue by ImAlreadyHope** [matthias-luger/hypixel-react#1017]
I would suggest to add group cards to the filter rules where you can drag filter objects inside to organize them properly.

On top of that i would add the option to move blacklist, whitelist objects around in the grid changing their order id to make sure that they can be placed the way you want them to be.

To make this all also easier to be used a search bar that can filter out based on keywords within the object would be really helpful too!

**Comment by matthias-luger** [comment]
This requires quite a lot of rewriting and it seems like the tags feature + the search functionality is enough for most people to search and organize their restrictions. Until more people complain about this or I see another reason for it, the current state should be enough.
