### ISSUE TITLE
Don't change Pet skin category 

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1023]
![Screenshot_2023-01-07-19-19-20-45_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://user-images.githubusercontent.com/16632490/211165056-1ab51bfb-9616-4fbb-b68b-282d3625bcb0.jpg)
This filter value should not be changed, it causes massive confusion.
It should be displayed as `Pet Skin (unapplied)`
To highlight it's unapplied pet skins.
https://github.com/Coflnet/SkyItems/blob/main/Models/ItemCategory.cs#L66

**Comment by Ekwav** [comment]
This still occurs in created elements
![image](https://user-images.githubusercontent.com/16632490/213876419-6ab81735-2309-412d-91c5-e66091aa65bb.png)

**Comment by matthias-luger** [comment]
should be fixed by #1044
