### ISSUE TITLE
Fix best flip preview 

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1040]
https://sky.coflnet.com/player/df2b974944b7416899a1ec1fe396519a/flips
There are two issues:
* The best flip is not the best flip (not sorted)
* The item name still contains formatting colors which should be removed

**Comment by matthias-luger** [comment]
@Ekwav What do you mean with "the best flip is not the best flip" part?
By default it is sorted by Time and sorting by profit it does indeed show me the flip with the highest profit on top
