### ISSUE TITLE
Switch bazaar buy and sell orders

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1067]
They are currently displayed the wrong way around.

**Comment by matthias-luger** [comment]
@Ekwav The reason for that seems to be that you send it to me in the wrong way. 

https://sky.coflnet.com/api/bazaar/BOOSTER_COOKIE/snapshot?timestamp=2023-03-01T11:54:03.819Z

![grafik](https://user-images.githubusercontent.com/58751503/222133163-6f942cb0-56d6-49fa-a0d5-ede315d1a57a.png)
![grafik](https://user-images.githubusercontent.com/58751503/222133246-e8214d15-f4bd-4dba-8872-51fc68f2b6af.png)

**Comment by Ekwav** [comment]
I know that they are returned in that order but that's not how its displayed in game.   
It needs to be switched to represent the same as in game (just switch the label as users probably got used to where the orders are)
