### ISSUE TITLE
Link bazaartracker

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#108]
Items that are only sold in the bazaar are not on hyauctions.
For all items that have the `bin` property set to `true` in the `pricerDicer` response `hyauction` link should be replace with a link to bazaartracker.com/product/{tag}

**Comment by matthias-luger** [comment]
a would like to have a other request-command for that (isInBazar?)
The pricerDicer is called in the PriceGraph. The options are in the Search-Component. So i cant really access it from there.

**Comment by Ekwav** [comment]
That would add another unnecessary request for every item.
Why is it so hard to get a variable to another component? 
Wouldn't it make sense to share `current` across components?
OptionsMenu would be a lot cleaner if it had access to the selected player/item.
You could use the endpoint `https://sky.coflnet.com/api/items/bazaar` to get all bazaar items and see if the Tag is in there.
Or you rely on the cache layer and request pricerdicer twice. 
But that also leads to additional requests.

**Comment by Ekwav** [comment]
I poted the http cache layer and exposed more item attributes (including `bazaar`) of the `itemDetails` command.
