### ISSUE TITLE
Add anniversary banner 

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1110]
Ticket to track the anniversary updates.

- [ ] Banner for mod
- [ ] Remove WIP
- [ ] Update delay time for free

**Comment by Ekwav** [comment]
https://github.com/Coflnet/hypixel-react/commit/9e85d14ef1de9a234764c871254d2bcf3b4cfed1 2 days

**Comment by matthias-luger** [comment]
@Ekwav What was the free tier delay reduced to again? 40 seconds?
