### ISSUE TITLE
Fix url search redirect

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1115]
/i/ItemName should redirect to the item tag instead of breaking.
The non next.js rendering did that but it appears that feature was not ported.

Example:
https://sky.coflnet.com/i/jerry-
should redirect to
https://sky.coflnet.com/item/JERRY_STAFF

Context:
https://discord.com/channels/267680588666896385/1113290687333539890/1113290691280371813

**Comment by matthias-luger** [comment]
fixed by eaa7d71e58f269db6a80771b2fff26b081ff6fc4
