### ISSUE TITLE
Missing master star 

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1116]
https://sky.coflnet.com/auction/74ba0359feb64564aad7683b982ece2c
The last star of this auction should be formatted red as the url preview indicate with §c

**Comment by matthias-luger** [comment]
Auction title: "§dAncient Necron's Leggings §6✪§6✪§6✪§6✪§6✪§c"

The §c is not followed by another star, therefore the last star is not colored red.

**Comment by Ekwav** [comment]
Alright misstook that, it's 6 stars in the NBT
