### ISSUE TITLE
Allow flip querying for more than a week

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1135]
`/api/flip/stats/player/{playerUuid}` now supports the query parameter `offset` (days)  
It should be possible to see more than the last week for all paying supporters.  
Querying for more than the last 7 days requires the Google token as `Authorization` header like the premium purchase endpoints do.

**Comment by matthias-luger** [comment]
https://songvoter.party/api/auth/google/code returns HTTP 500
Trace: songvoter-57f65777cd-q4sz4.1687866d9135bcd83c4c4e2a662337ae
