### ISSUE TITLE
0 is a valid filter value "none"

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1139]
![Image](https://user-images.githubusercontent.com/16632490/259553233-d64b0c66-6912-407d-8abf-297135146f60.png)

That is valid and "none" should be displayed when `0` is selected.
other numbers are also missng

**Comment by Ekwav** [comment]
https://sky-commands.coflnet.com/item/AURORA_CHESTPLATE?range=day&itemFilter=eyJtYW5hX3Bvb2wiOiIyLTIiLCJncm93dGgiOiIxLTMifQ%3D%3D

**Comment by matthias-luger** [comment]
fixed by 3271f0069cf7769c74daaef2d03a2c66fdea41be
