### ISSUE TITLE
Error not displayed

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1143]
This link should display the error returned by the api endpoint called (that filter is invalid without a rarity filter)
https://sky.coflnet.com/item/PET_GOLDEN_DRAGON?range=day&itemFilter=eyJQZXRMZXZlbCI6Ij4xMDAifQ%3D%3D

**Comment by matthias-luger** [comment]
fixed by d4966fa2d0057e3843efe3d378b3e836563b9d8a
