### ISSUE TITLE
Import fails when over 100 blacklist items

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1148]
Importing a blacklist currently fails if there are over 100 black or whitelisted items because the import tries to eager load all item names (which runs into the rate limit)
The import should not break if the api rate limit is reach but just defer loading all the item names. The item tag should be displayed until the name can be loaded at some point in the future (if the element enters the viewport for example)
Discord bug report with example file
https://discord.com/channels/267680588666896385/1149907589996490762/1150031266217996431

**Comment by matthias-luger** [comment]
@Ekwav Would it be possible to have a batch endpoint to get names for tags?

**Comment by Ekwav** [comment]
well yes, that is what `POST /api/items/names` is for

**Comment by matthias-luger** [comment]
@Ekwav I think I fixed the issue, but I think the linked config still invalid because of weird Rarity filters:
![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/12c3b93d-0c54-425f-bbeb-6997b386cb3b)

Are these some TFM things, I should remap?

**Comment by matthias-luger** [comment]
I was now told by the user who reported the issue that the config file was invalid. My import fix seems to work. Therefore I merge it
