### ISSUE TITLE
Unable to view new bazaar data

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1150]
https://sky.coflnet.com/item/THORN_FRAGMENT?range=hour
Switches to ah view

**Comment by matthias-luger** [comment]
@Ekwav 
https://sky.coflnet.com/api/item/price/THORN_FRAGMENT/history/hour returns HTTP 404
while
https://sky.coflnet.com/api/item/price/THORN_FRAGMENT/history/day return a empty array as I would expect it to.

Please send me a emtpy array for the "hour" request as well. Currently the website tries to show the default view (AH) with the "No data found" message after fetching new data fails.

**Comment by Ekwav** [comment]
Well that returns 404 because it doesn't exist, only `/api/bazaar/{itemTag}/history/hour` is a thing.
Hourly history only exists for bazaar items

**Comment by matthias-luger** [comment]
fixed by 8a329231af24a1afdde3db3c8ec9f2663cd4e013
