### ISSUE TITLE
Fix size of pannels

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1155]
On the start page `Ended Auctions` has a predictable size which should be fixed to reduce cumulative layout shift. Please also take a look at the small scroll bar on the right 

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/eb86276d-cc03-40e6-9c14-049908fb6ac2)

**Comment by matthias-luger** [comment]
fixed by f386ff0b3d5d6470ba6a1be0a9397afe4eda37f0
![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/dc599f7b-ce2d-4234-90c3-f0caeedb39dd)
