### ISSUE TITLE
Add a way to disable the disabling of the user finder on import

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1156]
Some of our power users readily import different settings and don't want to keep reenabling the user finder.
There should be an option for them to do that 
The enabling of that setting should only be kept in the browser.

**Comment by matthias-luger** [comment]
@Ekwav Where would you prefer this setting?
Putting it into the normal settings dialog seems unintuitive, as it's not exported with the other settings.
Also as it's only for "power users" it would not really hurt if its a bit more hidden, right?

So I would either add a new checkbox on the `/account` page, called something like "Remove risky finders on import".
Or put it into the normal settings with a notice that its not gonna get exported. -> Will probably cost quite a bit of space.

**Comment by Ekwav** [comment]
> @Ekwav Where would you prefer this setting? Putting it into the normal settings dialog seems unintuitive, as it's not exported with the other settings. Also as it's only for "power users" it would not really hurt if its a bit more hidden, right?
> 
> So I would either add a new checkbox on the `/account` page, called something like "Remove risky finders on import". Or put it into the normal settings with a notice that its not gonna get exported. -> Will probably cost quite a bit of space.

Its not an account setting so it makes no sense at the account page. I would expect it below the export/import buttons int the settings dialog or as a right-click option if you think it takes to much space

**Comment by matthias-luger** [comment]
@Ekwav This doesnt really belong to this issue, but what finders are still considered "risky"?
Currently there are warnings for TFM and Stonks to be risky/WIP. 
The import protection by default removes User and TFM though.
