### ISSUE TITLE
Add filter description

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1157]
The `/api/filter/options` endpoint received a new property `description` a while ago. Not every filter has a description yet but if it does it should be displayed/reachable somehow.
The description text contains a short explanation what a filter is/does filter for. 
If possible to search bar could also search the description text as ist sometimes contains aliases.

**Comment by matthias-luger** [comment]
fixed by a456dcce44a89b21fc3009c60c2b021486f30baa
