### ISSUE TITLE
Use loginWithToken to login when possible

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1161]
`setGoogle` now also returns `token` with a self signed token that can be used instead of `setGoogle` with `loginWithToken` to login.
That token can also be specified as `Authorization` header in all api requests that don't spend CoflCoins.

**Comment by matthias-luger** [comment]
@Ekwav Could you please remove the ok answer from the setGoogle request? My logic expects to only receive one answer, the following are getting ignored. 
![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/8647fd69-cc3e-4cf4-bf67-5c34a8151c63)

**Comment by Ekwav** [comment]
> @Ekwav Could you please remove the ok answer from the setGoogle request? My logic expects to only receive one answer, the following are getting ignored. ![grafik](https://user-images.githubusercontent.com/58751503/274092703-8647fd69-cc3e-4cf4-bf67-5c34a8151c63.png)

removed the ok

**Comment by matthias-luger** [comment]
@Ekwav Ich bekomme für `getCoflBalance` jedes mal andere (zufällige) Werte. Ich denke da ist was schief gelaufen:
![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/a4aeaac5-c2d6-47a3-90e9-d8f1e91d853c)
![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/1f51e9b6-b30a-40b2-8294-afc85efd992b)
![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/0f256d54-34de-492c-ba6d-f60eb4faf673)
![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/53a05238-a819-4d30-ab92-dde6c51691e9)
