### ISSUE TITLE
Don't display "you don't have premium" when not logged in

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1171]
![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/d115fb38-1960-4f90-af25-d3f96edc516d)

The current display causes a lot of confusion especially for people that don't see the Googlelogin button due to kaspersky or similar.
It should say "Unknown because not logged in" in orange/yellow maybe.

**Comment by matthias-luger** [comment]
fixed by dc2d3020daf485c821f918c2f35ce3c11e001103
