### ISSUE TITLE
Copy party command in trades does not work

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1187]
> When I click copy it gives me
> /p Tymamatyty I would like to buy your Rotten Flesh
> but that will try to invite Tymamatyty to the party
> but will also try to invite the player I, the player would, the player like etc
> Rather /p Tymamatyty would be the only way to make it work

The additional text should be removed from the button. Maybe adding another button or changing the button to copy the introduction text would be useful

**Comment by matthias-luger** [comment]
fixed by 843ca6fcc5f51ce64fa62f5c2b32b7c7f1bf3f3e
