### ISSUE TITLE
Add option to only show trade/non trades

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1188]
The flips page should have an option to toggle to only showing flips where the `ViaTrade` Flag is set.   
Related to https://github.com/Coflnet/hypixel-react/issues/1114 both flags now exist.  
There also is a third flag indicating if only one item or multiple were traded (price fraction is estimated in that case)

**Comment by matthias-luger** [comment]
Could you please provide a player having this Flag, so I can test it?

**Comment by Ekwav** [comment]
Of course :)  
Here is a flip link:  
https://sky.coflnet.com/api/flip/stats/player/e191dbc9-1f28-4609-b6e3-5ded5945eca9?start=2023-11-26T19%3A13%3A44&end=2023-11-26T19%3A13%3A45
