### ISSUE TITLE
Add option to specify coins on /trade

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1189]
For the `Have` side coins can be specified via a new property `coins`.   
For the `Want` side coins can be specified via `tag` `SKYBLOCK_COIN` and filter `Count` (to be in line with the other filter system)

**Comment by matthias-luger** [comment]
@Ekwav Creating a trade with the following data: ```[{"playerUuid":"cbf30125749d4134bba377e4f2d3a377","item":{"count":1,"description":"§7Speed: §a+1\n\n§7Your potato minions farm §a5%\n§a§7faster while wearing on your\n§7island.\n\n§7§8Forged by the Potato King\n§8after winning the Great Potato\n§8War.\n\n§f§lCOMMON ACCESSORY","enchantments":{},"extraAttributes":{"modifier":"superior","uid":"8748f3d476e6","uuid":"10e62941-241f-4df5-a9e5-8748f3d476e6","timestamp":"4/17/21 9:14 PM","tier":1},"icon":"https://sky.coflnet.com/static/icon/POTATO_TALISMAN","id":null,"itemName":"§fPotato Talisman","tag":"POTATO_TALISMAN"},"wantedItems":[{"itemName":"Aspect of the End","tag":"ASPECT_OF_THE_END"},{"itemName":"","tag":"SKYBLOCK_COIN","count":1,"description":"Coins","filters":{"COUNT":"234"}}]}]```

Returns: 
![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/56d9ca39-f95c-450c-accd-96da64d9686a)

**Comment by matthias-luger** [comment]
Still breaks 
![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/e2125023-8c94-477f-a7cf-cce098e6f251)

**Comment by Ekwav** [comment]
The filter is called `Count` and is case sensitive.
Its the same filter as for stackable items 

> Still breaks ![grafik](https://private-user-images.githubusercontent.com/58751503/286644866-e2125023-8c94-477f-a7cf-cce098e6f251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyOTM2MTQsIm5iZiI6MTcwMTI5MzMxNCwicGF0aCI6Ii81ODc1MTUwMy8yODY2NDQ4NjYtZTIxMjUwMjMtOGM5NC00NzdmLWE3Y2YtY2NlMDk4ZTZmMjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDIxMjgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OTgzMDFhZTAyZDdhZjVjZjc3YTRmZjM0ZGYxZGEyZTk1MmZmZTVlNzNjY2QwNTQwYTE5MTgxODA3ZjEyZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gzvs1GnuWeYDbWfjKsChT2sXxG4eJ_jhtTUbTNxOruE)
