### ISSUE TITLE
Add how-to button for verification to /ref

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1193]
https://sky.coflnet.com/ref mentions verification but doesn't explain yet how to do it.
There should be a button opening the same dialog as the claim account button on the player page.
Since it isn't user-dependent any more it should also be extended with the second video from the playlist in /mod showing exactly how to verify.
PS: /ref currently doesn't load when opened directly

**Comment by matthias-luger** [comment]
fixed by f81947a7e46fefed233fd2f2f9da4a8dba98cb6e
