### ISSUE TITLE
Add the flip duration

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1205]
![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/d2b3bd63-724e-4670-890e-73e09037e38a)

The time taken from purchase to sell should be displayed similar to the image.    
Link to suggestion:  
https://discord.com/channels/267680588666896385/1194796038746292297

**Comment by matthias-luger** [comment]
fixed e1f3948fc4cdb0b4f9d61cf8207138b3692bfdb5
