### ISSUE TITLE
Profit changes not obvious enough

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1206]
![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/da105604-14fb-4601-a968-61607d8861d9)

Its not directly obvious that there were profit changes (things added to the item) subtracted from cost.  
There should be a better indicator like partially showing the first or second profit change (one in the form of ah fees is always present and could be displayed instead of `Profit changes`)   
Partially showing it makes it apparent that there is more info.  
Example: https://css-tricks.com/text-fade-read-more/

**Comment by matthias-luger** [comment]
fixed by 74da353df5873001f7627b9fc39d2c66d2da6486
