### ISSUE TITLE
Make checkbox more obvious

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1207]
https://discord.com/channels/267680588666896385/1197591825947566222/1197592156991397929

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/150f450f-ed05-4a28-bcdb-b8fdccc1582a)

**Comment by matthias-luger** [comment]
Seems like darkreader doesn't set it's metatag correctly on the initial load. When turning darkreader on and off again, the meta-property is set. Gonna ask in their GitHub if this is intended.

**Comment by matthias-luger** [comment]
fixed by b8a90a9d3000c7a87d20ce88a16f44c76e919969
