### ISSUE TITLE
Make options more apparent

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1208]
I am often contacted by people purchasing the wrong type of plan.  
They should be differentiated more and/or none selected by default.

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/6924b13a-78fa-4917-8103-7b013a95c4eb)

**Comment by matthias-luger** [comment]
fixed by 990f81de34d0f9bb804a8c0cfd8c9f005147b6e0

It is still selected by default, but now way more obvious. If this should still not be enough, I unselect it by default
