### ISSUE TITLE
Bazaar all-time view stops in 2022

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1216]
All time view is broken for bazaar items eg: https://sky.coflnet.com/item/BOOSTER_COOKIE

It gets overriden with item request info (bazaar data is also loaded in network tab)

https://discord.com/channels/267680588666896385/1210797224154370109/1210797228218777630

**Comment by matthias-luger** [comment]
fixed by eca50d249f5302bec06bb829172193a849d3f54e
