### ISSUE TITLE
Profit based on `custom`

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1217]
If both lbin (sniper) and median (median sniper) are enabled the displayed value should be custom to highlight its neither of the two

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/c0bc9b83-5304-44fc-82d2-218fc4bd195b)

**Comment by matthias-luger** [comment]
fixed by 654afd5e013f9d3e6eaaba8ad25c1701d7b4cca4
