### ISSUE TITLE
Large owner history breaks

### ISSUE THREAD

**Issue by matthias-luger** [matthias-luger/hypixel-react#1221]
Large owner histories break because of too many request (HTTP 429)
Example: https://sky.coflnet.com/auction/439f76eb3c7f49c6b8bc0a40db0934d3
https://discord.com/channels/267680588666896385/1213204982791151617/1213215714924564540

**Comment by matthias-luger** [comment]
@Ekwav Please either add the buyer and seller IGNS to the `/auctions/uid/[uid]/sold` endpoint or provide a endpoint to batch-request usernames

**Comment by Ekwav** [comment]
Batch endpoint `/player/names` added since one of the major use cases is just finding the past sales its a separate endpoint.

**Comment by matthias-luger** [comment]
blocked by https://github.com/Coflnet/SkyApi/issues/113
