### ISSUE TITLE
Gemstone on bazaar has no graph

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1247]
https://sky.coflnet.com/item/FLAWLESS_OPAL_GEM?range=day  
There should be a graph displayed but currently isn't 

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/27c72b6e-3ac3-49ca-8aee-ff23870e29bf)

There is a response from the api with the datapoints I would expect so I assume its a bug in the frontend

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/92107bb1-a41f-418a-b4f2-74c6608584e9)

**Comment by matthias-luger** [comment]
fixed by 29983cf430571ec88b584bd455d9d4a174b089fc
