### ISSUE TITLE
Add Coin Equivilent to orders

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1256]
Bazaarflipper has requested that the coin equivalent for each order should be displayed like this 

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/eff6e0c6-6eca-4348-843a-e576967619a9)

**Comment by matthias-luger** [comment]
fixed by d6544345ac6e4f992836a781797450ae2d2a1e75
