### ISSUE TITLE
Copy error on click

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1260]
The reference should be copied if the error is clicked, followed by a green message that it got copied and the user should ask for help with it on discord. (best case the green error message should have the discord support channel link)

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/35580a74-1096-4ba9-9739-8b674df91359)

**Comment by matthias-luger** [comment]
@Ekwav It should already copy the trace when the toast message is clicked? Do you have a way I can get a error message for now, so I can test it?

**Comment by matthias-luger** [comment]
fixed by bd228f5e1334a079709b6ef1db53194ffe625f3c
