### ISSUE TITLE
Rename input field

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1266]
![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/1475252d-51c3-45bc-8a6a-559ab3ef7eac)

The `enter taget` should state `Discord Webhook Url (https://discord.com/api/...)` to clarify what to enter. Best case also make a plausibility check with the domain

**Comment by matthias-luger** [comment]
fixed by 513d2959e36c0ea791cdee5b2e4cf597ac45596f
