### ISSUE TITLE
Filter search missing a value

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1268]
![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/3270d79e-11d1-46d9-9bc7-ae6a7b4bd917)

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/d1f8312a-614f-4845-8a16-d3e9a451d1e6)

I would assume its because the searched value isn't the formatted form

https://discord.com/channels/267680588666896385/1246262810099449949/1246263051959668796

**Comment by matthias-luger** [comment]
fixed by 2c858dd6e481487d45760d41b726c079d52c36df
