### ISSUE TITLE
The anniversary balloon uses the image from last years crab hat

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1269]
https://sky.coflnet.com/item/BALLOON_HAT_2024?range=day uses images from item CRAB_HAT_IMAGES because they share the `party_hat_color` property.

The black color image is `https://mc-heads.net/head/63bdb1e21a9fdf98aff67f0ff4e7dfada05f340210dd70b688c09c3cf50f6410`

**Comment by Ekwav** [comment]
pink one: https://mc-heads.net/head/2ad4c874756ab9672aec51d53b9b94e6c9b5c6e7e0a2d44928df2186f4791e96

**Comment by matthias-luger** [comment]
fixed by f62f03c087562e79045567c3ad9b6fb40eb2130b
