### ISSUE TITLE
Filter overflow

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1276]
Filters should not be displayed on top of others.

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/014c8200-a2d3-450b-83c9-0c53f91f4e60)

https://discord.com/channels/267680588666896385/1254853443894382754/1256008963783393312

**Comment by matthias-luger** [comment]
fixed by 8e0de5454dceb1c4c4720709b0de2d86de3d3fa4
