### ISSUE TITLE
When format is emptied input field vanishes

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1277]
![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/fb21abda-ea5b-4a8a-af2d-7168b5b4ed5c)

https://discord.com/channels/267680588666896385/1256056935384485948/1256057003172958370

**Comment by matthias-luger** [comment]
fixed by 587ceeec34c0401f309629e66f02ac638b74ac09
