### ISSUE TITLE
Convert flatNbt Date to date

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1289]
On some items there is nbt data that is called `date` with a unix timestamp. E.g. https://sky.coflnet.com/auction/c590ac3eeff34611be5d50fdee043773
It should be converted to a localized date.

https://discord.com/channels/267680588666896385/1266539789562155122/1266539833329848382

**Comment by matthias-luger** [comment]
fixed by 5043798ace636a5992b6295328f6fbe63da319f5
