### ISSUE TITLE
Display if a purchase was a license

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1307]
For licenses the reference includes the minecraft uuid and session id separated by a `.` eg `384a029294fc445e863f2c42fe9709cb.60a3c83a-8f88-450e-b6a6-3f3d0ab7633a`  

There should be a visual difference/indicator that the purchase was not made on the account level and the website isn't affected by the purchase.

![Image](https://github.com/user-attachments/assets/4bb3c2c1-d4a7-4ec4-9881-f93f2add8f3a)

**Comment by Ekwav** [comment]
https://discord.com/channels/267680588666896385/1283253247900909659/1283253363269697648

**Comment by matthias-luger** [comment]
@Ekwav How exactly should this be implemented in your opinion?

If there is a "." in the middle of two Strings, I assume it is a license purchase?
And how "prominent" should it be displayed? Just in brackets behind the description, or heavily different in some form?

**Comment by Ekwav** [comment]
if its a dot and the first and second part are a uuid where the second one is dashed display a `(license for :firstuuid:)`
