### ISSUE TITLE
Add aka to prismatic

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1334]
The pristine enchant had the display name changed to prismatic, the website should reflect this in the auction details view. I would suggest displaying prismatic aka pristine in the enchant list
context:https://discord.com/channels/267680588666896385/1290723057366863933/1309552352637878403

**Comment by matthias-luger** [comment]
fixed by 9f498316a77b6ce003a7852eb37709f4324fdbb1
