### ISSUE TITLE
Integrate PayPal 

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#134]
Integrate PayPal as additional payment option.  
See
https://developer.paypal.com/docs/checkout/integrate/
and 
https://developer.paypal.com/docs/checkout/reference/server-integration/capture-transaction/#on-the-client

**Comment by matthias-luger** [comment]
@Flou21 When do you think you can start with this? This should be very simple (similar to the Stripe-Integration) and is quite important. If this boots the sales by 2-3 times like expected, we could think about a ios release.
