### ISSUE TITLE
Link to GitHub

### ISSUE THREAD

**Issue by nstringham** [matthias-luger/hypixel-react#200]
This is suggestion that there should be a link on the website to the GitHub repository of that website.

Linking to the GitHub on the website helps developers who would like to contribute to the website or users that would like to report bugs.

**Comment by Ekwav** [comment]
This repo is linked via https://sky.coflnet.com/about 
The site is called `Links/Legal` in the menu and reachable via every other page.
Where one the site did you expect the link to be?
