### ISSUE TITLE
Time is wrong

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#53]
All times in the auctionDetails site are displayed wrong. 
The Backend returns time as UTC wich isn't converted to the local timezone anywhere.

**Comment by matthias-luger** [comment]
It seems to be displayed correctly.
I get the UTC-Time and parse it to a Date-Object which seems to be correct.
And it is converted back to text with the toLocal-Functions. Please give an example of the wrong behaivor.
![image](https://user-images.githubusercontent.com/58751503/110256738-c7e07800-7f9a-11eb-90dd-af3acc004a88.png)

**Comment by Ekwav** [comment]
I talk about the relative time on the auctionDetails site.

**Comment by Ekwav** [comment]
Time for `auctionDetails` didn't return Time marked as UTC. (Z at the end, as visible in the Screenshot)
Backend now marks time as UTC
