### ISSUE TITLE
Reduce storage need

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#563]
The flipper tab was killed by my operating system. At the time it was killed it wrote 5GB/second to my NVMe. 
It should not need to write more than a few hundred kb at a time.
Please try to reduce the saving.

**Comment by matthias-luger** [comment]
It did what now O_o
I did never see that nor could I reproduct that. Could this be different behaivor with the virtualization libary for the list?

**Comment by Ekwav** [comment]
This appeared on other sites as well, I guess this is just my version of chrome.
