### ISSUE TITLE
Check filter usability

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#565]
https://discord.com/channels/267680588666896385/904017845623615520/904372889405501480

**Comment by matthias-luger** [comment]
The filters behave correctly in my opinion. The search-selects are meant to be selected after all, so the filter only activates after you select an item.

I think an apply button is only an unnecessary click and would annoy most users.
Are there any other specific complaints or change requests @glaicodes @Ekwav  ?
