### ISSUE TITLE
gui changes

### ISSUE THREAD

**Issue by glaicodes** [matthias-luger/hypixel-react#570]
maybe change bin and recomb filter to tick boxes, color the line seperating seller and end time ( highlited line in the picture)
![image](https://user-images.githubusercontent.com/75806392/139597772-7a54c4ba-5711-4e38-8397-c243a2a1f8e7.png) 
to the rarity of the item or the highest color enchant it has (if it has prot 7 the line will be red) or make the 2 next to each other

**Comment by glaicodes** [comment]
maybe divide that line to 5 and make them have different colors for different things (from left to right):
rarity (gray, green, blue, purple, orange, pink, light blue), hpb count (0-9 is gray, 10 is blue, 11-14 is purple, 15 is gold) stars are numbers 1-10, and maybe lastly, the highest tiered enchant it has (prot 5 is blue, 6 is purple, 7 is red) this is a poorly made example for this:
![ekran görüntüsü](https://user-images.githubusercontent.com/75806392/139598346-fb2ac934-a577-4cac-977d-e20874ca0690.png)

**Comment by glaicodes** [comment]
or this could be shown when hovered on it

**Comment by matthias-luger** [comment]
@glaicodes 
Just fyi, you can edit the things you wrote, so you dont have to make 3 posts.

I think the colored line is very confusing. What do you think about extra information like the "extra fields" in the flipper? 
![image](https://user-images.githubusercontent.com/58751503/139827917-1203215c-67bc-47e1-aabb-1cbd0c353648.png)

**Comment by glaicodes** [comment]
I like the small card design of the ah viewer. We can instead show the things that arent on the filters. Like 
![image](https://user-images.githubusercontent.com/75806392/139872893-92e6b0f6-c298-4e6c-af63-4049f47661f8.png)

this item has legion 5 which wasnt on the filter.

**Comment by matthias-luger** [comment]
waiting for https://github.com/Coflnet/SkyCommands/issues/24
