### ISSUE TITLE
issues on safari

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#594]
It was reported that the homepage could not be loaded on safari

**Comment by matthias-luger** [comment]
@Flou21 You have Safari right? Can you check this. Is there an error in the console, or does safari not support react?

**Comment by Flou21** [comment]
<img width="1021" alt="Screenshot 2021-11-20 at 08 46 42" src="https://user-images.githubusercontent.com/40125985/142718847-bf2083e2-28c8-4140-a359-9515fd8928de.png">

is this helpful?
