### ISSUE TITLE
No flips getting displayed

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#596]
There were multiple reports that no flips are displayed on the website.
I encountered this myself and worked around it by changing my settings so I assume its an issue with the `subFlip` command

**Comment by matthias-luger** [comment]
@Ekwav I think this is a backend issue? I cant see any difference between the subFlip messages I send you if it works and if it doesnt.

**Comment by Ekwav** [comment]
indeed it was, I ignored the command if you sent the same subFlip twice. 
Since you spammed the server with at least one subflip per minute I blocked duplicatus causing real resubs after page reload to fail.
