### ISSUE TITLE
Blacklist filter error

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#602]
When attempting to blacklist a pet with a specific rarity the option for rarity is missing

**Comment by matthias-luger** [comment]
I dont understand the bug.
![image](https://user-images.githubusercontent.com/58751503/143674743-bcb50b85-71af-4d76-81d9-c82999392f71.png)

**Comment by Ekwav** [comment]
Thanks, can't replicate it any more either
