### ISSUE TITLE
Add helpfull external sources

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#61]
Add links to external infromation.
PlayerSearch:
* [skycrypt](https://sky.shiiyu.moe/stats{uuid})
* [plancke](https://plancke.io/hypixel/player/stats/{uuid})
* [hyauctions](https://plancke.io/hypixel/player/stats/{uuid})

Item Prices:
* [wiki](https://hypixel-skyblock.fandom.com/wiki/{Item_Name_With_Underscore})

Since this could get very cluttered all these options should be moved to a popup menu (three-dots-vertical) preferably in the upper right of the screen.

**Comment by matthias-luger** [comment]
Three dots on the right top of the screen looks weird, because with #68 we already have the same icon on the top left. 
Also: Why do we want to link our competitors (excluding the wiki)???

**Comment by Ekwav** [comment]
I am open for alternative link locations (including alternative icons).
The three dots just usually mean "options" wich is fitting in my opinion.
We are linking our "competitors" because they provide valuable features we don't have. (wich means we aren't competing)
We can still remove a link, if you implement all the features these sites have.
