### ISSUE TITLE
Display Finder type with every flip

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#619]
People get confused by not being able to differentiate between the different flip finder types for each flip

**Comment by matthias-luger** [comment]
@Ekwav How should it be displayed. I initially planned to display it but was not sure about the importance of the finder type.
I thought of the following options:

- Colour (Header, Card, Copy-Button or all of them)
- Hover-Text
- As a  property in the props
- As a extra field

Which would you prefer?

**Comment by matthias-luger** [comment]
@Ekwav ping

**Comment by matthias-luger** [comment]
@Ekwav pong

**Comment by matthias-luger** [comment]
@Ekwav ping

**Comment by Ekwav** [comment]
Sorry, something seems wrong with my notifications.
I think a non eye catching (dark colored) badge next to volume with `FLIP` / `SNIPE` / `MSNIP`(or something better but as short) would be fitting 
Just changing the color of the card would be confusing as nobody would know what corresponds to what (except if they are changed everywhere)
