### ISSUE TITLE
authCon is sent before setGoogle

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#620]
The `authCon` command has to be sent after `setGoogle`.
The setConId doesn't have to be and shouldn't waited on for `setGoogle`

**Comment by matthias-luger** [comment]
@Ekwav  can't reproduce

**Comment by Ekwav** [comment]
Can't reproduce it anymore either in the production system.
For reference here is the bug report thread
https://discord.com/channels/267680588666896385/922140614257160242/922146693653352449
