### ISSUE TITLE
Display flip-errors 

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#633]
The server mostly enforces #632 already and returns errors on violation but errors are not displayed in any form.
This should be changed so errors are displayed in some form.

**Comment by matthias-luger** [comment]
@Ekwav How do you return me errors?
Subflip gets a ok-response for a invalid filter:

This filter had a minProfit of 72.540.584.888
![image](https://user-images.githubusercontent.com/58751503/147400386-98141bc2-c7cc-403d-a7e4-50251baa9944.png)

**Comment by matthias-luger** [comment]
@Ekwav ping

**Comment by matthias-luger** [comment]
@Ekwav pong

**Comment by matthias-luger** [comment]
@Ekwav ping

**Comment by Ekwav** [comment]
I can't reproduce your error.
Just tried again, can you give me the content of the whole message to test?
