### ISSUE TITLE
Make a profit tracking site 

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#641]
create a fancy UI for the profit tracking 
example url https://sky.coflnet.com/api/flip/stats/player/d74f804d46f94a61a8683995aef830fd
Its very important that the site has a good embed preview as well

**Comment by matthias-luger** [comment]
@Ekwav could I also get the tier (to format the name) and the tag (to get the image)

**Comment by Ekwav** [comment]
list of known finders https://github.com/Coflnet/HypixelSkyblock/blob/908800c66e6ffa8483d8b239e8762bf9fdcabec7/Data/Flipper/LowPricedAuction.cs#L23
