### ISSUE TITLE
Add new settings

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#659]
There are a few new settings.
Json keys:
* `mod.chat` enables the cofl chat by default
* `visibility.sellerOpenBtn` shows a button that opens the sellers ah
* `visibility.lore` shows the item lore when hovering chat
* `mod.format` Allows to change the mod format (is a string)

The default format is about the following:
"\n{0}: {1}{2} {3}{4} -> {5} (+{6} {7}) Med: {8} Lbin: {9} Volume: {10}"
                    {0} FlipFinder
                    {1} Item Rarity Color
                    {2} Item Name
                    {3} Price color
                    {4} Starting bid
                    {5} Target Price
                    {6} Estimated Profit
                    {7} Provit percentage
                    {8} Median Price
                    {9} Lowest Bin
                    {10}Volume
Every $ is replaced with § (formating prefix for minecraft)
There should be an editor which renders a message preview with the color library.

**Comment by matthias-luger** [comment]
@Ekwav are you sure, a normal user will understand this?
