### ISSUE TITLE
Add filters to price notifications

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#666]
Price notifications should be extended to include filters for properties.
The filter should be encoded as JSON string and set with property name `filter`
The max length of the filter field filter is 200 characters (about 3 filters)

**Comment by matthias-luger** [comment]
@Ekwav I get an error if I send this data with the subscribe-command:

'{"topic":"END_BOOTS","price":12,"type":2,"filter":{"Rarity":"UNCOMMON"}}'

**Comment by Ekwav** [comment]
> @Ekwav I get an error if I send this data with the subscribe-command:
> 
> '{"topic":"END_BOOTS","price":12,"type":2,"filter":{"Rarity":"UNCOMMON"}}'

that filter is not a string but an object. 
As stated above it should be serialized.

**Comment by matthias-luger** [comment]
@Ekwav it seems to work now, but I was able to subscribe to a filter with >200 characters
`'{"Reforge":"ancient","PetLevel":"4","Bin":"true","Stars":"3","HotPotatoCount":"15","UId":"234234234324","Recombobulated":"true","ArtOfTheWar":"yes","EnchantLvl":"6","Enchantment":"Any","EndAfter":"1560290400"}'`

Should I catch filters like that before, or can I expect you to send a error message back?

**Comment by Ekwav** [comment]
> @Ekwav it seems to work now, but I was able to subscribe to a filter with >200 characters
> `'{"Reforge":"ancient","PetLevel":"4","Bin":"true","Stars":"3","HotPotatoCount":"15","UId":"234234234324","Recombobulated":"true","ArtOfTheWar":"yes","EnchantLvl":"6","Enchantment":"Any","EndAfter":"1560290400"}'`
> 
> Should I catch filters like that before, or can I expect you to send a error message back?

Please catch it/say that no more than 6 filters are allowed
