### ISSUE TITLE
add custom filters for flips

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#676]
As you suggested I added custom filters only available for flips.
The command to retrieve options and available filters is `flipFilters` it has the same format as `filterFor`.

**Comment by matthias-luger** [comment]
@Ekwav Please give me the names in CamelCase.
Correct:
![image](https://user-images.githubusercontent.com/58751503/152892211-551b683b-f2b4-48ad-94ee-4b7b7d4d47c4.png)

FlipFilters:
![image](https://user-images.githubusercontent.com/58751503/152892255-58e80e4b-9b71-4e5f-9d9a-6d7249ef260a.png)

**Comment by Ekwav** [comment]
ok, rolling out the change
