### ISSUE TITLE
PayPal window closes unexpectedly in brave

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#704]
It's apparently not possible to buy premium on brave browser.

**Comment by matthias-luger** [comment]
@Ekwav doesnt seem to be the case anymore. Can you reproduce it in the new system?

**Comment by matthias-luger** [comment]
@Ekwav

**Comment by matthias-luger** [comment]
@Ekwav bump

**Comment by matthias-luger** [comment]
@Ekwav bump
