### ISSUE TITLE
Endless scroll breaks on big screens

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#706]
The endless scroll depends on the scroll event being triggered.
However on 4k screens the whole list of auctions or bids fits on screen which results in the user being unable to scroll.

Please also switch from /commands to using the /api while modifying the players page.

**Comment by matthias-luger** [comment]
@Ekwav How did you manage to do that? It works for my 4k screen...

**Comment by Ekwav** [comment]
> @Ekwav How did you manage to do that? It works for my 4k screen...

You can reproduce it on any screen size by scaling out.
I think also putting a "load more" button at the bottom would be good
