### ISSUE TITLE
Flipper page broke

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#711]
I commonly break the flipper page when I enable/disable flip finders
The popup modal stays but rest of the site turns black and becomes inresponsive
![image](https://user-images.githubusercontent.com/16632490/158876110-51912d7e-cf93-47f3-b855-cc9b06dcf92a.png)

**Comment by matthias-luger** [comment]
I could not reproduce this issue.
Is this still happening?

**Comment by matthias-luger** [comment]
@Ekwav bumb

**Comment by Ekwav** [comment]
could not reproduce it because I am unable to click the X
![image](https://user-images.githubusercontent.com/16632490/165508240-01a029de-0d01-4bd8-afc8-738f56195af3.png)
It looks like its rerendered multiple times a second

**Comment by matthias-luger** [comment]
@Ekwav I dont have / never had that issue. I just tired it again and it worked perfectly.
What Browser/Browser version are you using? Could you try it without your darkmode plugin? Don't know what else could mess with it...

**Comment by matthias-luger** [comment]
@Ekwav bump

**Comment by matthias-luger** [comment]
@Ekwav bump
