### ISSUE TITLE
Add a cancel button to the premium page

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#715]
There should be a big red cancel button that premium users can press to signal they don't want to renew premium. When clicked it should display information about that there currently is no subscription and that premium will end at the displayed time.
The button should be greyed out for users without premium and have the hover text `You currently don't have premium but could cancel it here`.
It serves the purpose of assuring users that they won't be locked into a subscription.

**Comment by matthias-luger** [comment]
@Ekwav  I would like to inform the user that a purchase is not a subscription beforehand. Also I dont like the idea of a cancel button if you dont need to cancel anything.

The initial Idea (while you were still in the VC) was this:
![image](https://user-images.githubusercontent.com/58751503/162644384-251705cf-978a-4ce5-b142-56b83f53e799.png)

I think this is better, as the user sees it before purchase:
![image](https://user-images.githubusercontent.com/58751503/162644416-3821faeb-7b54-42ba-ad22-fa8675088ef2.png)

Which one do you like more, or should we add both? Or do you dont like this approch at all?

**Comment by RobertCallens** [comment]
think this issue can get resolved since payment got reworked
