### ISSUE TITLE
Navigating around triggers dialog

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#734]
The "has an error occured" is triggered just by navigating around

**Comment by matthias-luger** [comment]
Please add a screenshot or better instructions to reproduce this

**Comment by matthias-luger** [comment]
@Ekwav bumb

**Comment by Ekwav** [comment]
I just click around the page ![Screenshot_2022-04-27-13-22-55-69_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://user-images.githubusercontent.com/16632490/165507923-d5dbb9df-ebd1-40b9-9ca3-e18b0045bca8.jpg)

**Comment by matthias-luger** [comment]
@Ekwav I can no longer reproduce this issue.
Can you? If so, please tell me what links/buttons you used to navigate.
