### ISSUE TITLE
Remember filters between sessions

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#745]
The filters should be remembered client side between sessions. Users commonly use the same filters and this would remove the need to reenter the filter values and be just one extra click to remove them in case they actually don't want them.

**Comment by matthias-luger** [comment]
@Ekwav  How "much" should I remember?
- only that for example that "Reforge: Sharp" was applied. And use that filter at any item if it has the Reforge-filter
- should I remember the filter <-> item, if so how many different filters should I remember
- only for the item search or should I also remember the last filters you set while adding some things to the blacklist (not a fan)

**Comment by Ekwav** [comment]
The filter should remember as much as possible to minimize the friction for future searches.
It may make sense to add a checkbox to disable the remembering or a dropdown to toggle from, remember all to remember last or remember same item
