### ISSUE TITLE
/p/username broken

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#767]
https://sky.coflnet.com/p/russianEXE should redirect to, but doesn't
https://sky.coflnet.com/player/62f79b343cec4795baf693838347685d

**Comment by matthias-luger** [comment]
@Ekwav I need an endpoint that gives me the uuid for the name of a user then. Or should I use the search endpoint?

**Comment by Flou21** [comment]
please fix that
@matthias-luger or @Ekwav
