### ISSUE TITLE
pricerdicer doesn't receive item tag

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#768]
This page doesn't display data https://sky.coflnet.com/item/INFERNO_HEAVY_CRUDE_GABAGOOL   
The command is called only with a start time
Please consider using `/api/item/price/{itemTag}/history/week` and `/api/item/price/{itemTag}/history/month` etc as well as `​/api​/auctions​/tag​/{itemTag}​/recent​/overview` (equivalent of recent auctions command)

As well as `​/api​/auctions​/tag​/{itemTag}​/active/overview`

**Comment by matthias-luger** [comment]
What should I call for all time?
There doesnt seem to be a endpoint for that

**Comment by matthias-luger** [comment]
@Ekwav

**Comment by matthias-luger** [comment]
Also:
The recentAuctions-Endpoint doesnt get the timespan or filter anymore?

**Comment by matthias-luger** [comment]
The recentAuctions-Endpoint doesnt include the seller name anymore.
Do you really want me to request every name in a seperate request?

Really dislike the new endpoints :(

**Comment by Ekwav** [comment]
Added new endpoints and updated the issue accordingly
