### ISSUE TITLE
Click on notification doesn't navigate if any other page is opened

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#81]
Happens when there is already a tab of https://sky.coflnet.com opened in the browser. Clicks on new notification will only focus this open tab and not navigate to the correct page.

**Comment by matthias-luger** [comment]
can reproduce

**Comment by Ekwav** [comment]
I guess you meant "can't"
Steps to reproduce:
1. Subscribe an item
2. wait until you get a notification
3. Click on it
4. Wait for a second notification
5. Click on it

You are still on the page of the first notification.
