### ISSUE TITLE
Color item stars 

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#810]
stars have special colors different from the item name (from rarity)
![image](https://user-images.githubusercontent.com/16632490/168889315-a407f88c-3889-4ece-853c-61a8c9bd948e.png)
they should be colored according to the value stored in nbt as `dungeon_item_level`
if the value is more than 5 the stars should be colored red one by one (they are called master stars then)
Except if there is a number next to it (eg https://sky.coflnet.com/auction/4c106884b7dd41c38f64e8f1caa25a0d )
then only the number should be red.  
also the special unicode symbol to display the number is hard to read, please try to improve that

**Comment by Ekwav** [comment]
another example of an item with master stars 
![image](https://user-images.githubusercontent.com/16632490/168890407-dc9fa97e-1061-45f2-992f-df9e9a3b65e7.png)

**Comment by matthias-luger** [comment]
@Ekwav What should I do at all the places I display item names (and stars) where I dont hae the dungeon_item_level?
This is the case on the startpage, flips and reference auctions

**Comment by Ekwav** [comment]
only apply the yellow format and red on the number then.
