### ISSUE TITLE
Simplify start settings

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#828]
New users commonly get confused/overwhelmed by the settings options. 
They should be simplified or restructured.
There should be a simple toggle that switches between lbin and median.

**Comment by matthias-luger** [comment]
@Ekwav Please provide a mockup, thanks :)

**Comment by Ekwav** [comment]
> @Ekwav Please provide a mockup, thanks :)


Sure, here you go, only took like 90 min :upside_down_face: 
![Untitled Diagram drawio](https://user-images.githubusercontent.com/16632490/175091664-eac017b2-2f56-48b9-bcaa-d07d093ccc5d.png)
