### ISSUE TITLE
Rarity filter sends empty values

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#834]
The `Rarity` filter defaults to an empty value, which is invalid, instead of the first option.
It should select the first option and never be an empty string

**Comment by matthias-luger** [comment]
Default selected values for search-selects were at one point removed on purpose. Just fyi.
![image](https://user-images.githubusercontent.com/58751503/174804434-fd09f309-4e67-4254-9cb1-fa6521f47dc5.png)
