### ISSUE TITLE
Item sites don't work

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#836]
I suppose there is an issue with bazaar data but 
1. I don't know what to fix
2. A user doesn't know anything just gets a broken site
This is what I get when navigating to an item page
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/16632490/174473152-29679076-7894-42bb-885f-f21d75b6cb2e.png">
this is what I get when trying to open the page or Pressing F5
<img width="517" alt="image" src="https://user-images.githubusercontent.com/16632490/174473176-a0faac4e-cb8a-4199-99f1-753e592b3305.png">

**Comment by matthias-luger** [comment]
Should be fixed
