### ISSUE TITLE
So many not updated listings.

### ISSUE THREAD

**Issue by glaicodes** [matthias-luger/hypixel-react#857]
It's self explanatory.

for example: https://sky.coflnet.com/auction/37851bf780c943e3ae084075f0a0416e
https://sky.coflnet.com/auction/e653d22eccf348f49738b221b05b9817

Maybe its possible to make a force refresh that would get new data of the listing from the api

**Comment by matthias-luger** [comment]
@glaicodes What do you mean with "not updated"?
Also: Requesting the data again would do the same as refreshing the page.
