### ISSUE TITLE
Filter is not actually added

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#861]
Some filters (eg. Is shiny) are not applied until they are changed.
Filters that have a default selection should be applied when they are added

**Comment by matthias-luger** [comment]
@Ekwav I fixed this some time ago. Apparently it was not live, I just promoted the frontend.
It was fixed with this: https://github.com/Coflnet/hypixel-react/commit/8dd5b769e5bbd89740a335f02274dc1437567b06
