### ISSUE TITLE
Add mayor history overlay

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#874]
It should be possible to display the active mayor in addition/instead of the date to visualize price changes the go along with them.

**Comment by matthias-luger** [comment]
@Ekwav Only to be sure: You don't use the `/api/mayor?from=x&to=y` endpoint, right? Cause I changed it so it also includes election periods that are only partially in the given timespan.

**Comment by matthias-luger** [comment]
fixed by 9c536a154202cedde60fcfcc9788185fa5832b79
