### ISSUE TITLE
tem data

### ISSUE THREAD

**Issue by Flou21** [matthias-luger/hypixel-react#876]
we are hosting the tem database for more than 4 months

here is a little api i just started:
![Screenshot 2022-07-21 at 23 28 07](https://user-images.githubusercontent.com/40125985/180318235-1372b894-1da3-48b0-950b-124eb484682b.png)

https://sky.coflnet.com/api/tem/swagger/index.html

UI would be good

**Comment by matthias-luger** [comment]
@Flou21 Doesnt seem to work anymore

**Comment by Flou21** [comment]
i will look into that later
