### ISSUE TITLE
/mod page

### ISSUE THREAD

**Issue by matthias-luger** [matthias-luger/hypixel-react#881]
- Details about the mod
- Videos with the mod
- Link to github
- Rat checker

**Comment by Ekwav** [comment]
To retrieve the md5 hash this could be used: https://github.com/satazor/js-spark-md5#hash-a-file-incrementally
and then send it to vytals api 
https://isthisarat.com/api/signature/<md5 hash>
if there are no matches it returns 
`{"rat": "No matching signature", "md5return": md5} ` (then display a link to the homepage)
If its a known good/bad mod display the result. The format is `{"rat": <Yes or No>, "md5return": md5hash}`
