### ISSUE TITLE
Default recent auctions to sold

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#882]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/16632490/182025601-f715c3b6-c1ba-4448-9ade-61b881303980.png">
Most people expect to see sold auctions because the graph also only shows sold ones

**Comment by matthias-luger** [comment]
fixed https://github.com/Coflnet/hypixel-react/commit/209b43f3696d42b3576cd1f927f7655fda5006f7
