### ISSUE TITLE
price chart not displaying

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#884]
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/16632490/182172320-ef0bac80-d21e-4ec2-b915-a90d8edeea57.png">
the data is loaded from the server but not displayed

**Comment by ThomasWu931** [comment]
I tried replicating this error on coflnet.com however found that the graph data was displayed. @Ekwav, did you by chance do anything special to get the bug? (Maybe something to do with changing the filtering config for exp)

**Comment by Ekwav** [comment]
I intended to check which shard attributes are worth what amount but couldn't.   
I now could not replicate it when trying a few minutes ago. Seems to have gone away.  
Gonna reopen this when I encounter it again.
