### ISSUE TITLE
Disappearing filters

### ISSUE THREAD

**Issue by ThomasWu931** [matthias-luger/hypixel-react#887]
### The isssue

Clicking `close` on an item filer seems  to remove all of the set filter options from the UI. Note that this removal is purely visual as refreshing would bring back the set filtering options. 

### How to Replicate Error
1. Search up an item (Exp: Aspect of the End)
2. Click `Add Filter`
3. Click a filter (Exp: Reforger)
4. Click `Close`
5. Click `Add Filter`
6. Now the set filter dissappears

**Comment by ThomasWu931** [comment]
As a note about this bug, I'm not fully what the intended behaviour is. If I had to guess, I'd assume that step 6 should redisplay the filter with the filter from step 3. 

If this is the intended behaviour, then I'm a little confused over why we require the `selectedFilters` field. The reason is because why not just use `itemFilter` instead? It seems that selectedFilters makes it so that only certain entries from `itemFilter` are displayed on the filter. However, does the current app intend to support such a feature?

**Comment by matthias-luger** [comment]
fixed the issue with https://github.com/Coflnet/hypixel-react/commit/7f46160e47ca5fb9b13ed8eab9f44dc80cb6bb58

**Comment by matthias-luger** [comment]
I think you are right and ´selectedFilters´ could be removed and refactored to Object.keys(itemFilter).
I think the initial implementation was made by Ekwav over a year ago. I just never bothered refactoring it (and still dont).

If you really want to, you can change it and submit a PR, but I am focusing on other things right now.
