### ISSUE TITLE
Checkbox not visible

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#888]
The checkbox should be visible also for people with darkreader. 
<img width="942" alt="image" src="https://user-images.githubusercontent.com/16632490/183510218-c824d8bf-dccd-4112-be63-b602ef56822c.png">

At least one of our users got very confused https://discord.com/channels/267680588666896385/1005918405536264253/1005919219445137449

**Comment by matthias-luger** [comment]
What should I do if someone installs a external tool that makes things hard to see / invisible?
As far as I have seen, there is nothing I can add to tell this extension not to change this element. I could create a PR in their repository to add our page to a blocklist, but I dont think darkreader users would like that as well.
I also dont want to make the checkboxes greyish by default and hope that darkreader leaves them in peace. That would make it harder to read for everybody

**Comment by matthias-luger** [comment]
Should be fixed now...
The checkboxes are now shown in grey, if I detect the darkreader extension
