### ISSUE TITLE
Claim Account? Text not visible on mobile

### ISSUE THREAD

**Issue by Flou21** [matthias-luger/hypixel-react#895]
The "You? Claim Account" Message is not visible on mobile devices

pls fix

**Comment by matthias-luger** [comment]
It does for me tough...
![Screenshot_20220828-225314_Chrome 1165](https://user-images.githubusercontent.com/58751503/187094113-59d153b2-69ba-487d-a7d4-9009290b9734.jpg)

**Comment by matthias-luger** [comment]
it was not shown, because you were not logged in. Changed that :)
