### ISSUE TITLE
Can't paste into search on mobile chrome

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#898]
The report dialog opens when long pressing the search bar.  
The dialog should only open when long pressing the result.  
![image](https://user-images.githubusercontent.com/16632490/186528508-c18b236c-c4df-415b-afe9-ac4d442ae03f.png)

**Comment by matthias-luger** [comment]
fixed https://github.com/Coflnet/hypixel-react/commit/a621c88e92f2c0b7ba43467c0c49afc81e6b3f85
