### ISSUE TITLE
Display that it might take a few minutes for the payment to process on /success

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#908]
Quite a few users get confused by the coins being not immediately available after purchase

**Comment by matthias-luger** [comment]
Does it really? I thought they get it instantly, but it is not automatically getting updated yet (which should be fixed with https://github.com/Coflnet/hypixel-react/pull/892)

**Comment by Ekwav** [comment]
> Does it really? I thought they get it instantly, but it is not automatically getting updated yet (which should be fixed with #892)

Yes, the response from the payment provider is asynchronous
