### ISSUE TITLE
Show correct crab hat images

### ISSUE THREAD

**Issue by matthias-luger** [matthias-luger/hypixel-react#910]
https://discord.com/channels/267680588666896385/1017881303158366319/1017882761085853799

**Comment by matthias-luger** [comment]
@Ekwav Do we have images of differently colored hats? If so, what are the tags?

**Comment by matthias-luger** [comment]
@Ekwav bump

**Comment by Ekwav** [comment]
> @Ekwav Do we have images of differently colored hats? If so, what are the tags?

as mentioned in the next message after the one linked in the issue description, all crab hats are the same item.  
> all crab hats are the same item on hypixels site, it only differs in the nbt data

If there were different images/items/tags I could handle that from the backend.
