### ISSUE TITLE
Reduce flicker

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#92]
All elements should be created with fixed height (and width).
They may be filled with placeholders and later replaced with text.
Placeholders are just gray rectangles.
This reduces irritating flickering when loading and gives the perception that the page is loading faster

**Comment by Ekwav** [comment]
@matthias-luger The cumulative layout shift is the seemingly the only reason why https://sky.coflnet.com is not listed in google search results.

**Comment by matthias-luger** [comment]
do you have any more ideas for reducing flickering
Placeholders didnt seem to work that well. I once again tried it with quite accurate boxes (AuctionList) and lighthouse still didnt like it.

Please give me a list of ideas to try out.
