### ISSUE TITLE
Add button to refresh blacklist titles

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#923]
Items like the one introduced with the nether update in April started out saying `not on ah` but they are actionable and would have a different title now.

![Image](https://user-images.githubusercontent.com/16632490/191561348-f81a1d45-47af-4f3d-b15e-3c205d379cec.png)

there should be a button like the `Clear list` to refresh all entries on the blacklist for new titles.

**Comment by matthias-luger** [comment]
@Ekwav Is there a endpoint that accepts a list of tags, or do you really that I try to potentially send >100 requests at once (that would get blocked, right?)

**Comment by Ekwav** [comment]
There is no endpoint batch requesting names. I expected you to trigger a request for each item. Since they are likely already in the browser/cdn/api cache they won't be rate limited.

**Comment by Ekwav** [comment]
* correction, there is https://sky.coflnet.com/api/items I also added `POST` https://sky.coflnet.com/api/items/names which takes an array of item tags
