### ISSUE TITLE
Allow paying users to display more auctions

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#961]
![image](https://user-images.githubusercontent.com/16632490/197576055-096ce229-6bbd-427d-9d9b-56c6497a725a.png)
Users with starter premium or higher should get more than the default 12 results.  
The two api endpoints for recent and active auctions support pagination of up to 10 pages.  
Users with starter premium should get up to 60 results and users with premium or higher 120.  
There should be a note for users without premium that they can get more results by supporting the project with starter premium.  (Equivalent message for starter premium users scrolling all the way down to the end of their 60)   
Also add the feature to the /premium comparison table

**Comment by matthias-luger** [comment]
@Ekwav Are the 2 endpoints live yet? I only found these two, both dont accept pages: 
![image](https://user-images.githubusercontent.com/58751503/197657454-46ab183d-6d3e-40ae-8211-e11c961e310d.png)
![image](https://user-images.githubusercontent.com/58751503/197657486-60ce5bc9-d9ae-45ce-8ef6-07ec1831097f.png)

**Comment by Ekwav** [comment]
Yes the page is a custom filter. It got implemented a few months ago.
You can see the source here: https://github.com/Coflnet/SkyApi/blob/main/Controllers/AuctionsController.cs#L120
It's not listed because it's all URL based get parameters.
