### ISSUE TITLE
Use itemName on /crafts

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#966]
Currently the tag (internal hypixel name) is used to infer the item name. The `itemName` property should be used instead.
Note: It is prefixed with the color code of the item.

**Comment by matthias-luger** [comment]
Is it possible for you to just send me a "tier" property like for flips and other auctions I have to color?
The current way would be messy:

- The libary to convert the minecraft codes into html returns HTML objects whitch I can only add into the component with useRef-Hooks (not really possible with an array) or dangerouslySetInnerHTML (not cool). I guess I could also add it in by ignoring react alltogether (getElementById...) but that would also not be cool
- The first letter of the item name is lower case. In theory I would have to format the name after converting it to the html object. Which would be messy again (or substring it out before) => could also be prevented by just sending me the name and tier

**Comment by Ekwav** [comment]
> Is it possible for you to just send me a "tier" property like for flips and other auctions I have to color?
> The current way would be messy:
> 
> - The libary to convert the minecraft codes into html returns HTML objects whitch I can only add into the component with useRef-Hooks (not really possible with an array) or dangerouslySetInnerHTML (not cool). I guess I could also add it in by ignoring react alltogether (getElementById...) but that would also not be cool
> - The first letter of the item name is lower case. In theory I would have to format the name after converting it to the html object. Which would be messy again (or substring it out before) => could also be prevented by just sending me the name and tier

Why should the the color code be split from the name on the backend instead of on the frontend.
You don't have to color it, just remove the color codes if you don't.
The item name is returned with color from the dataset.
