### ISSUE TITLE
Seach doesnt find Shadow Assasin Chestplate

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#971]
The search doesnt find the shadow assasin chestplate. You are only able to find it by manually editing the URL (https://sky.coflnet.com/item/SHADOW_ASSASSIN_CHESTPLATE?range=day).

The request: https://sky.coflnet.com/api/search/shadow%20assasin%20chestplate

![Image](https://user-images.githubusercontent.com/58751503/199752223-2fa5659e-67e4-4f21-8454-b50ce4b86170.png)

**Comment by Ekwav** [comment]
@matthias-luger thats because you forgot an s in assassin
`shadow assassin chestplate` <- correct
`shadow assasin chestplate` <-- your search

how should such typos be filtered?

**Comment by matthias-luger** [comment]
I dont think you can account for every typo...
Sorry, that was a mistake on my part
